#
# Service Discovery - Consul
#
consul:
  command: -server -bootstrap -advertise 10.0.0.100 -ui-dir /ui
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"
  restart: always

#
# Service Discovery - Registrator
#
registrator:
  command: -ip=10.0.0.100 consul://consul:8500 -e SERVICE_IGNORE=always
  image: gliderlabs/registrator:v4
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
  restart: always
